### ISSUE TITLE
Mac OS Indefinite Loading

### ISSUE THREAD

**Issue by HamiltonJMC** [Serubin/PulseClient-Legacy#3]
Just a heads-up; in the Mac OS app, once I log into my account, a loading animation plays indefinitely. I am running Mac OS 10.12.6.

**Comment by Serubin** [comment]
If you press Cmd+R after you log in. What happens?
Also, does this occur in a browser as well?

**Comment by HamiltonJMC** [comment]
Cmd+R refreshes the page, but that page continues to be a loading animation. The issue does not occur in-browser (Chrome). As the loading animation plays, the only option that can be selected that does anything is Log Out. Logging out and logging back in resumes the loading screen only.

**Comment by Serubin** [comment]
If you don't mind helping me out:

When you open the app, go to the view menu in the apple status bar and click `toggle developer tools`. Under that there should be a "console" menu.

If you could open that and press reload in the app and copy and past any thing that goes into the console log that would be **super**.

**Comment by HamiltonJMC** [comment]
To make it a bit more readable:
http://i.imgur.com/NIZ4Apk.png

**Comment by Serubin** [comment]
Ah. Because of the global color setting it was erroring. Should be fixed as of cab6810
You may need to clear the cache of the desktop app, but the fix is live.
